#!/bin/bash

num=`ps aux|rg '[^rg]alacritty \-\-class dropdown_alacritty'|wc -l`
if [ $num -gt 0 ]
  then
    i3-msg '[instance="dropdown_alacritty"] scratchpad show'
  else
    alacritty --class dropdown_alacritty -e /usr/bin/fish -c "tmux attach-session -t 'dropdown' || tmux new -s 'dropdown'" &
fi
