#!/bin/bash

num=`ps aux|rg '[^rg]alacritty \-\-class dropdown_alacritty'|wc -l`
if [ $num -gt 0 ]
  then
    i3-msg '[instance="dropdown_alacritty"] scratchpad show'
  else
    tmux has-session -t dropdown 2>/dev/null
    if [ $? -ne 0 ]; then
      tmux new-session -s dropdown -n vb -d
      tmux move-window -t 9
      tmux send-keys -t 9 "vb" Enter
      tmux new-window -t 0
    fi
    alacritty --class dropdown_alacritty -e /usr/bin/fish -c "tmux attach-session -t dropdown" &
fi
