#!/bin/bash

tmux () {

}

num=`ps aux|rg '[^rg]alacritty \-\-class main_alacritty'|wc -l`
if [ $num -gt 0 ]
  then
    i3-msg '[instance="main_alacritty"] scratchpad show'
  else
    alacritty --class main_alacritty -e /usr/bin/fish -c "tmux attach-session -t 'main' || tmux new -s 'main'" &
fi
