icons_format = "{icon}"

[theme]
theme = "modern"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome4"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "battery"
device = "hid-dc:2c:26:2f:52:58-battery"
format = " $icon KB $percentage "
full_format = " $icon KB $percentage "
missing_format = ""

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $play $next |}"

[[block]]
block = "net"
device = "wlp0s20f3"
# format = "{ssid} {signal_strength}{speed_down}{speed_up}"
format = " ^icon_net_wireless ^icon_net_down$speed_down.eng(p:K) ^icon_net_up$speed_up.eng(p:K) "
missing_format = ""

[[block]]
block = "net"
device = "enp7s0"
# format = "Ethernet{speed_down}{speed_up}"
format = "$icon ^icon_net_down$speed_down.eng(p:K) ^icon_net_up$speed_up.eng(p:K) "
missing_format = ""

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:3,u:B,p:G) ($mem_used_percents.eng(w:2)) "
format_alt = " $icon_swap $swap_used.eng(w:3,u:B,p:G)/$swap_total.eng(w:2,u:B,p:G) ($swap_used_percents.eng(w:1)) "

[[block]]
block = "disk_space"
path = "/"
# # alias = "/"
info_type = "available"
alert_unit = "GB"
# # unit = "GB"
# # interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
# format = "{1m}"

[[block]]
block = "temperature"
format = " $icon $average "

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time "
full_format = " $icon 100% "

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
